/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSalesReportRouteImport } from './routes/_authenticated/sales-report'
import { Route as AuthenticatedRepresentativesRouteImport } from './routes/_authenticated/representatives'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedProductionRouteImport } from './routes/_authenticated/production'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedMaterialsRouteImport } from './routes/_authenticated/materials'
import { Route as AuthenticatedMaterialStockRouteImport } from './routes/_authenticated/material-stock'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedDeletedOrdersRouteImport } from './routes/_authenticated/deleted-orders'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDailyProductionRouteImport } from './routes/_authenticated/daily-production'
import { Route as AuthenticatedDailyConsumptionRouteImport } from './routes/_authenticated/daily-consumption'
import { Route as AuthenticatedCostRouteImport } from './routes/_authenticated/cost'
import { Route as AuthenticatedBomRouteImport } from './routes/_authenticated/bom'
import { Route as AuthenticatedArchiveOrdersRouteImport } from './routes/_authenticated/archive-orders'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSalesReportRoute =
  AuthenticatedSalesReportRouteImport.update({
    id: '/sales-report',
    path: '/sales-report',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRepresentativesRoute =
  AuthenticatedRepresentativesRouteImport.update({
    id: '/representatives',
    path: '/representatives',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductionRoute = AuthenticatedProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMaterialsRoute = AuthenticatedMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMaterialStockRoute =
  AuthenticatedMaterialStockRouteImport.update({
    id: '/material-stock',
    path: '/material-stock',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDeletedOrdersRoute =
  AuthenticatedDeletedOrdersRouteImport.update({
    id: '/deleted-orders',
    path: '/deleted-orders',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDailyProductionRoute =
  AuthenticatedDailyProductionRouteImport.update({
    id: '/daily-production',
    path: '/daily-production',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDailyConsumptionRoute =
  AuthenticatedDailyConsumptionRouteImport.update({
    id: '/daily-consumption',
    path: '/daily-consumption',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCostRoute = AuthenticatedCostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBomRoute = AuthenticatedBomRouteImport.update({
  id: '/bom',
  path: '/bom',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedArchiveOrdersRoute =
  AuthenticatedArchiveOrdersRouteImport.update({
    id: '/archive-orders',
    path: '/archive-orders',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/archive-orders': typeof AuthenticatedArchiveOrdersRoute
  '/bom': typeof AuthenticatedBomRoute
  '/cost': typeof AuthenticatedCostRoute
  '/daily-consumption': typeof AuthenticatedDailyConsumptionRoute
  '/daily-production': typeof AuthenticatedDailyProductionRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deleted-orders': typeof AuthenticatedDeletedOrdersRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/material-stock': typeof AuthenticatedMaterialStockRoute
  '/materials': typeof AuthenticatedMaterialsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/production': typeof AuthenticatedProductionRoute
  '/products': typeof AuthenticatedProductsRoute
  '/representatives': typeof AuthenticatedRepresentativesRoute
  '/sales-report': typeof AuthenticatedSalesReportRoute
  '/users': typeof AuthenticatedUsersRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/archive-orders': typeof AuthenticatedArchiveOrdersRoute
  '/bom': typeof AuthenticatedBomRoute
  '/cost': typeof AuthenticatedCostRoute
  '/daily-consumption': typeof AuthenticatedDailyConsumptionRoute
  '/daily-production': typeof AuthenticatedDailyProductionRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deleted-orders': typeof AuthenticatedDeletedOrdersRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/material-stock': typeof AuthenticatedMaterialStockRoute
  '/materials': typeof AuthenticatedMaterialsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/production': typeof AuthenticatedProductionRoute
  '/products': typeof AuthenticatedProductsRoute
  '/representatives': typeof AuthenticatedRepresentativesRoute
  '/sales-report': typeof AuthenticatedSalesReportRoute
  '/users': typeof AuthenticatedUsersRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/archive-orders': typeof AuthenticatedArchiveOrdersRoute
  '/_authenticated/bom': typeof AuthenticatedBomRoute
  '/_authenticated/cost': typeof AuthenticatedCostRoute
  '/_authenticated/daily-consumption': typeof AuthenticatedDailyConsumptionRoute
  '/_authenticated/daily-production': typeof AuthenticatedDailyProductionRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/deleted-orders': typeof AuthenticatedDeletedOrdersRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/material-stock': typeof AuthenticatedMaterialStockRoute
  '/_authenticated/materials': typeof AuthenticatedMaterialsRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/production': typeof AuthenticatedProductionRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/representatives': typeof AuthenticatedRepresentativesRoute
  '/_authenticated/sales-report': typeof AuthenticatedSalesReportRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/archive-orders'
    | '/bom'
    | '/cost'
    | '/daily-consumption'
    | '/daily-production'
    | '/dashboard'
    | '/deleted-orders'
    | '/inventory'
    | '/material-stock'
    | '/materials'
    | '/orders'
    | '/production'
    | '/products'
    | '/representatives'
    | '/sales-report'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/archive-orders'
    | '/bom'
    | '/cost'
    | '/daily-consumption'
    | '/daily-production'
    | '/dashboard'
    | '/deleted-orders'
    | '/inventory'
    | '/material-stock'
    | '/materials'
    | '/orders'
    | '/production'
    | '/products'
    | '/representatives'
    | '/sales-report'
    | '/users'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/archive-orders'
    | '/_authenticated/bom'
    | '/_authenticated/cost'
    | '/_authenticated/daily-consumption'
    | '/_authenticated/daily-production'
    | '/_authenticated/dashboard'
    | '/_authenticated/deleted-orders'
    | '/_authenticated/inventory'
    | '/_authenticated/material-stock'
    | '/_authenticated/materials'
    | '/_authenticated/orders'
    | '/_authenticated/production'
    | '/_authenticated/products'
    | '/_authenticated/representatives'
    | '/_authenticated/sales-report'
    | '/_authenticated/users'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sales-report': {
      id: '/_authenticated/sales-report'
      path: '/sales-report'
      fullPath: '/sales-report'
      preLoaderRoute: typeof AuthenticatedSalesReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/representatives': {
      id: '/_authenticated/representatives'
      path: '/representatives'
      fullPath: '/representatives'
      preLoaderRoute: typeof AuthenticatedRepresentativesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/production': {
      id: '/_authenticated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthenticatedProductionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/materials': {
      id: '/_authenticated/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof AuthenticatedMaterialsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/material-stock': {
      id: '/_authenticated/material-stock'
      path: '/material-stock'
      fullPath: '/material-stock'
      preLoaderRoute: typeof AuthenticatedMaterialStockRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/deleted-orders': {
      id: '/_authenticated/deleted-orders'
      path: '/deleted-orders'
      fullPath: '/deleted-orders'
      preLoaderRoute: typeof AuthenticatedDeletedOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daily-production': {
      id: '/_authenticated/daily-production'
      path: '/daily-production'
      fullPath: '/daily-production'
      preLoaderRoute: typeof AuthenticatedDailyProductionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daily-consumption': {
      id: '/_authenticated/daily-consumption'
      path: '/daily-consumption'
      fullPath: '/daily-consumption'
      preLoaderRoute: typeof AuthenticatedDailyConsumptionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cost': {
      id: '/_authenticated/cost'
      path: '/cost'
      fullPath: '/cost'
      preLoaderRoute: typeof AuthenticatedCostRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bom': {
      id: '/_authenticated/bom'
      path: '/bom'
      fullPath: '/bom'
      preLoaderRoute: typeof AuthenticatedBomRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/archive-orders': {
      id: '/_authenticated/archive-orders'
      path: '/archive-orders'
      fullPath: '/archive-orders'
      preLoaderRoute: typeof AuthenticatedArchiveOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedArchiveOrdersRoute: typeof AuthenticatedArchiveOrdersRoute
  AuthenticatedBomRoute: typeof AuthenticatedBomRoute
  AuthenticatedCostRoute: typeof AuthenticatedCostRoute
  AuthenticatedDailyConsumptionRoute: typeof AuthenticatedDailyConsumptionRoute
  AuthenticatedDailyProductionRoute: typeof AuthenticatedDailyProductionRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDeletedOrdersRoute: typeof AuthenticatedDeletedOrdersRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedMaterialStockRoute: typeof AuthenticatedMaterialStockRoute
  AuthenticatedMaterialsRoute: typeof AuthenticatedMaterialsRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedProductionRoute: typeof AuthenticatedProductionRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedRepresentativesRoute: typeof AuthenticatedRepresentativesRoute
  AuthenticatedSalesReportRoute: typeof AuthenticatedSalesReportRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedArchiveOrdersRoute: AuthenticatedArchiveOrdersRoute,
  AuthenticatedBomRoute: AuthenticatedBomRoute,
  AuthenticatedCostRoute: AuthenticatedCostRoute,
  AuthenticatedDailyConsumptionRoute: AuthenticatedDailyConsumptionRoute,
  AuthenticatedDailyProductionRoute: AuthenticatedDailyProductionRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDeletedOrdersRoute: AuthenticatedDeletedOrdersRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedMaterialStockRoute: AuthenticatedMaterialStockRoute,
  AuthenticatedMaterialsRoute: AuthenticatedMaterialsRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedProductionRoute: AuthenticatedProductionRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedRepresentativesRoute: AuthenticatedRepresentativesRoute,
  AuthenticatedSalesReportRoute: AuthenticatedSalesReportRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
